apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage0
  namespace: netcatlab
  labels:
    app: stage0
spec:
  selector:
    matchLabels:
      app: stage0
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stage0
    spec:
      containers:
        - name: stage0
          image: webterminal
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CURRENT_STAGE
              value: stage0
            - name: UNLOCK
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: terminalUnlock
            - name: GOTTY_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: stage0gotty
            - name: FLAGTXT
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: stage0curl
---
apiVersion: v1
kind: Service
metadata:
  name: stage0
  namespace: netcatlab
spec:
  type: LoadBalancer
  selector:
    app: stage0
  ports:
  - name: webterminal
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: flask
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: netcat
    protocol: TCP
    port: 2222
    targetPort: 2222