apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage4
  namespace: netcatlab
  labels:
    app: stage4
spec:
  selector:
    matchLabels:
      app: stage4
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stage4
    spec:
      containers:
        - name: stage4
          image: webterminal
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CURRENT_STAGE
              value: stage4
            - name: UNLOCK
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: stage3Unlock
            - name: GOTTY_CREDENTIAL
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: stage4gotty
            - name: FLAGTXT
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: stage4curl
---
apiVersion: v1
kind: Service
metadata:
  name: stage4
  namespace: netcatlab
spec:
  type: LoadBalancer
  selector:
    app: stage4
  ports:
  - name: webterminal
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: flask
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: netcat
    protocol: TCP
    port: 2222
    targetPort: 2222