apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal
  namespace: netcatlab
  labels:
    app: terminal
spec:
  selector:
    matchLabels:
      app: terminal
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: terminal
    spec:
      containers:
        - name: terminal
          image: webterminal
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: CURRENT_STAGE
              value: terminal
            - name: NEXT_FLAG
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: terminalUnlock
            - name: FLAGTXT
              valueFrom:
                secretKeyRef:
                  name: netcatlab-secrets
                  key: terminalcurl
---
apiVersion: v1
kind: Service
metadata:
  name: terminal
  namespace: netcatlab
spec:
  type: LoadBalancer
  selector:
    app: terminal
  ports:
  - name: webterminal
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: flask
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: netcat
    protocol: TCP
    port: 2222
    targetPort: 2222