apiVersion: v1
kind: Secret
metadata:
  name: netcatlab-secrets
  namespace: netcatlab
type: Opaque
data:
  terminalcurl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTA6NTAwMCBpcyAnd2VsY29tZScK # The flag to submit to http://stage0:5000 is 'welcome'
  terminalUnlock: d2VsY29tZQ==  # welcome

  stage0gotty: ZmxhZzplbnRyeXBvaW50 # flag:entrypoint
  stage0curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTE6NTAwMCBpcyAnUG9ydFNjYW5uaW5nJwo= # The flag to submit to http://stage1:5000 is 'PortScanning'
  stage0Unlock: UG9ydFNjYW5uaW5n # PortScanning

  stage1gotty: ZmxhZzpSZXZlcnNlU2hlbGw= # flag:ReverseShell
  stage1curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTI6NTAwMCBpcyAnTmV0Y2F0U2hlbGwnCg== # The flag to submit to http://stage2:5000 is 'NetcatShell'
  stage1Unlock: TmV0Y2F0U2hlbGw= # NetcatShell

  stage2gotty: ZmxhZzpOZXR3b3JrUmVkaXJlY3Rpb24= # flag:NetworkRedirection
  stage2curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTM6NTAwMCBpcyAnRmlsZVRyYW5zZmVyJw== # The flag to submit to http://stage3:5000 is 'FileTransfer'
  stage2Unlock: RmlsZVRyYW5zZmVy # FileTransfer

  stage3gotty: ZmxhZzpDb21tYW5kRXhlY3V0aW9u #flag:CommandExecution
  stage3curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTQ6NTAwMCBpcyAnQmluZFNoZWxsJwo= # The flag to submit to http://stage4:5000 is 'BindShell'
  stage3Unlock: QmluZFNoZWxs # Bindshell

  stage4gotty: ZmxhZzpMaXN0ZW5Nb2Rl # flag:ListenMode
  stage4curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTU6NTAwMCBpcyAnVHVubmVsaW5nJwo= # The flag to submit to http://stage5:5000 is 'Tunneling'
  stage4Unlock: VHVubmVsaW5n # Tunneling

  stage5gotty: ZmxhZzpFbmNyeXB0ZWRDb21tcw== # flag:EncryptedComms
  stage5curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTY6NTAwMCBpcyAnUmVtb3RlQWRtaW4n # The flag to submit to http://stage6:5000 is 'RemoteAdmin'
  stage5Unlock: UmVtb3RlQWRtaW4= # RemoteAdmin

  stage6gotty: ZmxhZzpOZXR3b3JrRXhwbG9yYXRpb24= # flag:NetworkExploration
  stage6curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTc6NTAwMCBpcyAnVGNwVWRwQ29ubmVjdGlvbicK # The flag to submit to http://stage7:5000 is 'TcpUdpConnection'
  stage6Unlock: VGNwVWRwQ29ubmVjdGlvbg== # TcpUdpConnection

  stage7gotty: ZmxhZzpEYXRhRXhmaWw= # flag:DataExfil
  stage7curl: VGhlIGZsYWcgdG8gc3VibWl0IHRvIGh0dHA6Ly9zdGFnZTg6NTAwMCBpcyAnTmV0d29ya1NuaWZmaW5nJwo= # The flag to submit to http://stage8:5000 is 'NetworkSniffing'
  stage7Unlock: TmV0d29ya1NuaWZmaW5n # NetworkSniffing

  stage8gotty: ZmxhZzpSZW1vdGVBY2Nlc3M= # flag:RemoteAccess
  stage8curl: V2VsbCB5b3UgbWFkZSBpdCB0aGlzIGZhci4gIFRoZXJlIGlzIG5vIHN0YWdlOSBjb25zb2xlIHRvIHVubG9jay4gIE5vdyB5b3UgbXVzdCBzZXR1cCBhIG5hbWVkcGlwZSBhbmQgbmV0Y2F0IHBpdm90IG9uIGVhY2ggc3RhZ2UgYWxvbmcgdGhlIHdheS4gIEZyb20gJ3Rlcm1pbmFsJyBhY2Nlc3MgdGhlIHdlYnNlcnZlciBvbiBzdGFnZTkgZm9yIHRoZSBmaW5hbCBmbGFnIQ==
  # Well you made it this far.  There is no stage9 console to unlock.  Now you must setup a namedpipe and netcat pivot on each stage along the way.  From 'terminal' access the webserver on stage9 for the final flag!
  stage8Unlock: QmFja2Rvb3I= # Backdoor

  stage9curl: T25jZSB1cG9uIGEgdGltZSwgaW4gdGhlIGVhcmx5IGRheXMgb2YgdGhlIGludGVybmV0LCBhIG15c3RlcmlvdXMgaGFja2VyIGtub3duIG9ubHkgYXMgIkhvYmJpdCIgZW1lcmdlZCBmcm9tIHRoZSBzaGFkb3dzIGFuZCB1bmxlYXNoZWQgYSBwb3dlcmZ1bCB0b29sIHVwb24gdGhlIHdvcmxkLiBUaGlzIHRvb2wgd2FzIGNhbGxlZCAibmV0Y2F0LCIgYW5kIGl0IHF1aWNrbHkgYmVjYW1lIGtub3duIGFzIHRoZSAiU3dpc3MgQXJteSBrbmlmZSIgb2YgbmV0d29ya2luZyB1dGlsaXRpZXMuDQoNCldpdGggaXRzIHNpbXBsZSBjb21tYW5kLWxpbmUgaW50ZXJmYWNlLCBuZXRjYXQgYWxsb3dlZCB1c2VycyB0byBlYXNpbHkgcmVhZCBhbmQgd3JpdGUgZGF0YSBhY3Jvc3MgbmV0d29ya3MsIG1ha2luZyBpdCBhIGZhdm9yaXRlIGFtb25nIHNlY3VyaXR5IHByb2Zlc3Npb25hbHMsIG5ldHdvcmsgYWRtaW5pc3RyYXRvcnMsIGFuZCBoYWNrZXJzIGFsaWtlLiBJdHMgdmVyc2F0aWxpdHkgYW5kIHBvd2VyIG1hZGUgaXQgdGhlIGdvLXRvIHRvb2wgZm9yIGV2ZXJ5dGhpbmcgZnJvbSB0cm91Ymxlc2hvb3RpbmcgbmV0d29yayBpc3N1ZXMgdG8gY3JlYXRpbmcgYmFja2Rvb3JzIGZvciBhY2Nlc3NpbmcgcmVtb3RlIHN5c3RlbXMuDQoNCkJ1dCBhcyB3aXRoIGFsbCBwb3dlcmZ1bCB0b29scywgbmV0Y2F0IGFsc28gYXR0cmFjdGVkIHRoZSBhdHRlbnRpb24gb2YgdGhvc2Ugd2l0aCBtYWxpY2lvdXMgaW50ZW50LiBJdCB3YXMgdXNlZCBpbiBjb3VudGxlc3MgY3liZXIgYXR0YWNrcywgYW5kIHNvb24gZWFybmVkIGEgcmVwdXRhdGlvbiBhcyBhICJoYWNrZXIncyB0b29sLiINCg0KRGVzcGl0ZSB0aGlzLCBuZXRjYXQncyBwb3B1bGFyaXR5IG9ubHkgY29udGludWVkIHRvIGdyb3cuIEl0cyBvcGVuLXNvdXJjZSBuYXR1cmUgZW5zdXJlZCB0aGF0IGl0IHdhcyBjb25zdGFudGx5IGJlaW5nIHVwZGF0ZWQgYW5kIGltcHJvdmVkIHVwb24gYnkgYSBkZWRpY2F0ZWQgY29tbXVuaXR5IG9mIGRldmVsb3BlcnMuDQoNCkFzIHRoZSBpbnRlcm5ldCBldm9sdmVkLCBzbyBkaWQgbmV0Y2F0LiBJdCByZW1haW5zIHRvIHRoaXMgZGF5IGEgcG93ZXJmdWwgYW5kIHdpZGVseS11c2VkIHRvb2wsIGJvdGggZm9yIGdvb2QgYW5kIGZvciBpbGwuIEFuZCB0aGUgbGVnZW5kIG9mIEhvYmJpdCBhbmQgaGlzIGNyZWF0aW9uIGxpdmVzIG9uLCBhIHRlc3RhbWVudCB0byB0aGUgZW5kdXJpbmcgaW1wYWN0IHRoYXQgYSBzaW5nbGUgaW5kaXZpZHVhbCBhbmQgYSBzaW5nbGUgdG9vbCBjYW4gaGF2ZSBvbiB0aGUgd29ybGQuDQoNCi0gVGhlIE5ldGNhdCBiYWNrc3RvcnkgYXMgd3JpdHRlbiBieSBDaGF0R1BUDQo=
  